name: holy_word_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.1.0

  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  http: ^1.2.0
  url_launcher: ^6.2.5
  share_plus: ^12.0.1
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.2
  intl: ^0.20.2
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/database/
