name: holy_word_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.1.0

  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  http: ^1.2.0
  url_launcher: ^6.2.5
  share_plus: ^12.0.1
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.2
  intl: ^0.20.2
  scrollable_positioned_list: ^0.3.8
  image_picker: ^1.2.1
  auto_size_text: ^3.0.0
  flutter_colorpicker: ^1.1.0
  pdf: ^3.11.3
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/database/
    - assets/fonts/

  fonts:
    - family: Annamayya
      fonts:
        - asset: assets/fonts/annamayya.otf
        - asset: assets/fonts/annamayya_bold.otf
          weight: 700
    - family: Dhurjati
      fonts:
        - asset: assets/fonts/dhurjati.otf
    - family: Gidugu
      fonts:
        - asset: assets/fonts/gidugu.otf
    - family: Gurajada
      fonts:
        - asset: assets/fonts/gurajada.otf
    - family: LakkiReddy
      fonts:
        - asset: assets/fonts/lakkireddy.ttf
    - family: Mallanna
      fonts:
        - asset: assets/fonts/mallanna.otf
    - family: Mandali
      fonts:
        - asset: assets/fonts/mandali_regular.ttf
        - asset: assets/fonts/mandali_bold.ttf
          weight: 700
    - family: Nandakam
      fonts:
        - asset: assets/fonts/nandakam.otf
    - family: NATS
      fonts:
        - asset: assets/fonts/nats.otf
    - family: NTR
      fonts:
        - asset: assets/fonts/ntr.otf
    - family: Peddana
      fonts:
        - asset: assets/fonts/peddana_regular.ttf
    - family: Potti Sreeramulu
      fonts:
        - asset: assets/fonts/potti_sreeramulu.ttf
    - family: Ramabhadra
      fonts:
        - asset: assets/fonts/ramabhadra_regular.ttf
    - family: Ramaneeyawin
      fonts:
        - asset: assets/fonts/ramaneeyawin.ttf
    - family: RaviPrakash
      fonts:
        - asset: assets/fonts/raviprakash.ttf
    - family: Sree Krushnadevaraya
      fonts:
        - asset: assets/fonts/sree_krushnadevaraya.otf
    - family: Suranna
      fonts:
        - asset: assets/fonts/suranna_regular.otf
        - asset: assets/fonts/suranna_bold.otf
          weight: 700
    - family: Suravaram
      fonts:
        - asset: assets/fonts/suravaram.otf
    - family: Syamala Ramana
      fonts:
        - asset: assets/fonts/syamala_ramana.otf
